routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Meals
Route::resource('meal', 'MealController');
//facebook login
Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderFacebookCallback');

app/Meal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meal extends Model
{
    protected $fillable = [
        'name', 'date'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'token', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MealController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\Meal as MealResource;
use Illuminate\Http\Request;
use App\Meal;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
class MealController extends Controller
{
    //  public function __construct()
    // {
    //     $this->middleware('auth:admin', ['except'=>['index','show']]);
    // }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      //order by ascending date
        $meals = Meal::orderBy('date','desc')->paginate(7);
        return MealResource::collection($meals);
        //return view('meals.indexMeal')->with('meals', $meals);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      $meal = $request->isMethod('put') ? Meal::findOrFail
      ($request->id) : new Meal;
      $meal->name = $request->input('name');
      $meal->date = $request->input('date');

      if($meal->save()){
        return new MealResource($meal);
      }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function addToCart($id)
    {

        return Redirect::to('meal/create');
    }
    public function show($id)
    {
        //get meal
        $meal = Meal::findOrFail($id);
        return new MealResource($meal);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meals = Meal::find($id);
       return view('meals.editMeal')->with('meals',$meals);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        // validate
        // read more on validation at http://laravel.com/docs/validation
        $rules = array(
            'name'       => 'required',
            'date'      => 'required|date',

        );
        $validator = Validator::make(Input::all(), $rules);

        // process the login
        if ($validator->fails()) {
            return Redirect::to('meal/create')
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        } else {
            // store
            $meal = Meal::find($id);
            $meal->name       = Input::get('name');
            $meal->date      = Input::get('date');

            $meal->save();

            // redirect
            Session::flash('message', 'Successfully created nerd!');
            return Redirect::to('meal/create');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         // delete
        $meal = Meal::findOrFail($id);
        if($meal->delete()){
          return new MealResource($meal);
        }


    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">

                  <body>

                   <div id="app">
                     <div class="row">
                       <meals></meals>

                     </div>

                   </div>
  </body>


                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                  <img style="border-radius: 50%;height:42px; width:42px" src='{{ Auth::user()->avatar }}'>

                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/meals/createMeal.blade.php
@extends('layouts.app')
@section('content')
<div style="float: left;">
<h1>Create Meal</h1>
 <div class="form-group" >
       <form action="{{route('meal.store')}}" method="POST" id="createMealID">
       	@csrf
       	<div class="form-group">
       		<label>Data</label>
       		<input type="date" name="date">
       	</div>
   		<div class="form-group">
   			<label>Nome</label>
    		<textarea rows="4" cols="50" name="name" >
    		</textarea>
		</div>
  		<input type="submit" value="Submit">
       </form>
    	
   
    </div>
</div>
    <div style="float: right;padding-right: 400px">
    <table> @foreach($meals as $key => $value)
     
        <tr>
            <td>{{ $value->date }}</td>
            <td>{{ $value->name }}</td>



            <!-- we will also add show, edit, and delete buttons -->
            <td>

             {{ Form::open(array('route' => array('meal.destroy', $value->id), 'method' => 'delete')) }}
				    <button class="btn btn-small btn-danger" type="submit">Delete Meal</button>
				    

                <!-- edit this nerd (uses the edit method found at GET /meal/{id}/edit -->
                <a class="btn btn-small btn-info" href="{{ URL::to('meal/' . $value->id . '/edit') }}">Edit Meal</a>
				{{ Form::close() }}
                <!-- show the nerd (uses the show method found at GET /meal/{id} -->
                

            </td>
        </tr></div>
    @endforeach
</table>
@endsection

resources/views/meals/editMeal.blade.php
@extends('layouts.app')
@section('content')
<div style="float: left;">
<h1>Create Meal</h1>
{{$meals}}
 <div class="form-group" >

 	 {{ Form::open(array('route' => array('meal.update', $meals->id), 'method' => 'put')) }}
		<div class="form-group">
       		<label>Data</label>
       		<input type="date" name="date" value="{{$meals->date}}">
       	</div>
   		<div class="form-group">
   			<label>Nome</label>
    		<textarea rows="4" cols="50" name="name"  >
    			{{$meals->name}}
    		</textarea>
		</div>
  		<input type="submit" value="Submit"> 
		{{ Form::close() }}

       
     
    </div>
</div>
    
</table>
@endsection

resources/views/meals/indexMeal.blade.php
@extends('layouts.app')
@section('content')
<h1>Meal index</h1>
   <table> @foreach($meals as $key => $value)

        <tr>
            <td>{{ $value->id }}</td>
            <td>{{ $value->name }}</td>
<div id="app">
  <meals></meals>
</div>
            <!-- we will also add show, edit, and delete buttons -->
<td>
  <!-- show the meals (uses the show method found at GET /meal/{id} -->
  <a class="btn btn-small btn-success" href="{{route('meal.show' , $value->id)}}" >Show this Neddrd</a>
</td>
</tr>
    @endforeach
</table>
<script src="{{asset:js/app.js}}"> </script>
@endsection